### ISSUE TITLE
Error: The requested platform 'ZP' was not registered by any plugin.

### ISSUE THREAD

**Issue by gr4z** [ebaauw/homebridge-zp#100]
Hi. 
Recently installed homebridge and cannot get past this issue.  Installed via sudo npm -g i homebridge-lib homebridge-zp.

Config file:
`        {
            "platform": "ZP",
            "name":"Sonos",
            "service": "fan",
            "brightness": false,
            "speakers": false
        },`

Also notice this in the logs:
_Error: Plugin /usr/lib/node_modules/homebridge-zp requires a HomeBridge version of ^0.4.50 which does not satisfy the current HomeBridge version of 0.4.49. You may need to upgrade your installation of HomeBridge_

Which is incorrect as I am definitely using 0.4.50

Any ideas? Thanks

**Comment by ebaauw** [comment]
As of v1.0.x, homebridge-lib is once again a regular dependency.  Install homebridge-zp by `sudo npm -g i homebridge-zp` (without homebridge-lib).

You probably have multiple installations of homebridge.  How do you start Homebridge?  What does `homebridge -V` report?  Homebridge doesn't load the plugin because of the version conflict, so it doesn't register the `ZP` platform.
