### ISSUE TITLE
Unpredictable volume setting in Sonos Groups

### ISSUE THREAD

**Issue by keycized** [ebaauw/homebridge-zp#117]
The only reason I use homeridge and homebridge-zp is to set a different volume in a Sonos group. 
I have Sonos speakers in my bathroom and bedroom. The volume in the bathroom must be higher than in the bedroom. So I set up two scenes with Eve. One of them puts the two speakers back into a group every night. The other scene sets a higher volume in the bathroom one minute after the alarm. The alarm is provided by the Sonos functionality. 
However, when the volume in the bathroom is increased, the volume in the bedroom is also changed. The only action I select in the scene is the brightness of the Bath Speaker. 
When I run this scene I can see in the log file that not only is the brightness of the bathroom speaker set, but the brightness of the Sonos bedroom is also increased. 
I have already tried to re-create the scene. Without success. 
For a while the whole setup went fine. Since I upgraded the plugins, I have this problem. Now I have also upgraded Node to a higher version. Which did not fix the problem.
The problem seems to occur only with grouped speakers.
Any ideas or recommendations?
Thanks

**Comment by ebaauw** [comment]
This is how Sonos works:
- When you change the volume of a zone, the volume of the corresponding zone group is adjusted to reflect the average volume of the zones in that zone group;
- When you change the volume of a zone group, the volume of all member zones is adjusted.

Note that the _Volume_ (_Brightness_) in the _Sonos_ service reflects the group volume and the _Volume_ (_Brightness_) in the _Speakers_ service reflects the zone volume.  See the README.

**Comment by keycized** [comment]
Thanks for the answer.

That means, if I explicitly set the volume on both speakers (via Speaker Service), can I achieve different volume levels on both speakers?
Unfortunately, if I set up and trigger such a scene, it won't work. I will have the same volume on the Sonos volume for both speakers.

**Comment by ebaauw** [comment]
Did you setup the scene in Eve?  This should work; I'm using this daily.

Could you please capture a debug log file when activating the HomeKit scene?  Please attach the file here.  See https://github.com/ebaauw/homebridge-hue#debug-log-file.

**Comment by keycized** [comment]
Yes, I use Eve to setup the scenes.

I tried to capture the debug log and extracted the interesting part.

In my test setup I Initially set the volume for both speaker in the Sonos app to 4%.
The Eve scene should set the bathroom volume to 27% and the bedroom to 13%. Activating the scene sets the volume correctly, but just a second later the volume on both speakers is set to 20%.

Hope the log file extract will help.

Dec 26 09:18:46 raspberrypi homebridge[14615]: [12/26/2019, 09:18:46] [Sonos] RINCON_7828CAF166A001400 [Schlafzimmer]: event: NOTIFY MediaRenderer/GroupRenderingControl/Event
Dec 26 09:18:46 raspberrypi homebridge[14615]: [12/26/2019, 09:18:46] [Sonos] RINCON_347E5C2262A401400 [Bad]: event: NOTIFY MediaRenderer/RenderingControl/Event
Dec 26 09:18:46 raspberrypi homebridge[14615]: [12/26/2019, 09:18:46] [Sonos] Bad Speakers: set Brightness from 5% to 4%
Dec 26 09:18:46 raspberrypi homebridge[14615]: [12/26/2019, 09:18:46] [Sonos] RINCON_7828CAF166A001400 [Schlafzimmer]: event: NOTIFY MediaRenderer/GroupRenderingControl/Event
Dec 26 09:18:46 raspberrypi homebridge[14615]: [12/26/2019, 09:18:46] [Sonos] Schlafzimmer Sonos: set Brightness from 5% to 4%
Dec 26 09:18:46 raspberrypi homebridge[14615]: [12/26/2019, 09:18:46] [Sonos] Bad Sonos: set Brightness from 5% to 4%
Dec 26 09:20:20 raspberrypi homebridge[14615]: [12/26/2019, 09:20:20] [Sonos] RINCON_347E5C2262A401400 [Bad]: lastSeen: 94s ago at 192.168.1.35, bootSeq: 20
Dec 26 09:20:20 raspberrypi homebridge[14615]: [12/26/2019, 09:20:20] [Sonos] RINCON_5CAAFDFD5A1001400 [K<C3><BC>che]: lastSeen: 297s ago at 192.168.1.36, bootSeq: 14
Dec 26 09:20:20 raspberrypi homebridge[14615]: [12/26/2019, 09:20:20] [Sonos] RINCON_7828CAF166A001400 [Schlafzimmer]: lastSeen: 94s ago at 192.168.1.40, bootSeq: 15
Dec 26 09:20:20 raspberrypi homebridge[14615]: [12/26/2019, 09:20:20] [Sonos] RINCON_7828CAF1600A01400 [Wohnzimmer]: lastSeen: 293s ago at 192.168.1.39, bootSeq: 19
Dec 26 09:20:20 raspberrypi homebridge[14615]: [12/26/2019, 09:20:20] [Sonos] RINCON_347E5C2262A401400 [Bad]: lastSeen: 94s ago at 192.168.1.35, bootSeq: 20
Dec 26 09:20:20 raspberrypi homebridge[14615]: [12/26/2019, 09:20:20] [Sonos] RINCON_5CAAFDFD5A1001400 [K<C3><BC>che]: lastSeen: 297s ago at 192.168.1.36, bootSeq: 14
Dec 26 09:20:20 raspberrypi homebridge[14615]: [12/26/2019, 09:20:20] [Sonos] RINCON_7828CAF166A001400 [Schlafzimmer]: lastSeen: 94s ago at 192.168.1.40, bootSeq: 15
Dec 26 09:20:20 raspberrypi homebridge[14615]: [12/26/2019, 09:20:20] [Sonos] RINCON_7828CAF1600A01400 [Wohnzimmer]: lastSeen: 293s ago at 192.168.1.39, bootSeq: 19
Dec 26 09:21:06 raspberrypi homebridge[14615]: [12/26/2019, 09:21:06] [Sonos] Bad Speakers: Brightness changed from 4% to 27%
Dec 26 09:21:06 raspberrypi homebridge[14615]: [12/26/2019, 09:21:06] [Sonos] RINCON_347E5C2262A401400 [Bad]: request 9: POST /MediaRenderer/RenderingControl/Control SetVolume
Dec 26 09:21:06 raspberrypi homebridge[14615]: [12/26/2019, 09:21:06] [Sonos] Schlafzimmer Speakers: Brightness changed from 5% to 13%
Dec 26 09:21:06 raspberrypi homebridge[14615]: [12/26/2019, 09:21:06] [Sonos] RINCON_7828CAF166A001400 [Schlafzimmer]: request 8: POST /MediaRenderer/RenderingControl/Control SetVolume
Dec 26 09:21:07 raspberrypi homebridge[14615]: [12/26/2019, 09:21:07] [Sonos] RINCON_347E5C2262A401400 [Bad]: request 9: status 200
Dec 26 09:21:07 raspberrypi homebridge[14615]: [12/26/2019, 09:21:07] [Sonos] RINCON_7828CAF166A001400 [Schlafzimmer]: request 8: status 200
Dec 26 09:21:07 raspberrypi homebridge[14615]: [12/26/2019, 09:21:07] [Sonos] RINCON_7828CAF166A001400 [Schlafzimmer]: event: NOTIFY MediaRenderer/RenderingControl/Event
Dec 26 09:21:07 raspberrypi homebridge[14615]: [12/26/2019, 09:21:07] [Sonos] RINCON_347E5C2262A401400 [Bad]: event: NOTIFY MediaRenderer/RenderingControl/Event
Dec 26 09:21:07 raspberrypi homebridge[14615]: [12/26/2019, 09:21:07] [Sonos] RINCON_7828CAF166A001400 [Schlafzimmer]: event: NOTIFY MediaRenderer/GroupRenderingControl/Event
Dec 26 09:21:07 raspberrypi homebridge[14615]: [12/26/2019, 09:21:07] [Sonos] Schlafzimmer Sonos: set Brightness from 4% to 20%
Dec 26 09:21:07 raspberrypi homebridge[14615]: [12/26/2019, 09:21:07] [Sonos] Bad Sonos: set Brightness from 4% to 20%

**Comment by keycized** [comment]
Here is the log file. beginning with the restart of the HomeKit server.
[homebridge.log](https://github.com/ebaauw/homebridge-zp/files/4002174/homebridge.log)

And the scene in Eve
![IMG_2598](https://user-images.githubusercontent.com/59224461/71471344-7ef63680-27cf-11ea-81f2-08c0ff068390.PNG)

**Comment by ebaauw** [comment]
Please attach the full log file.

**Comment by keycized** [comment]
So you think the setup should work as expected? 
In the meantime I observed something odd in the home app. For every speaker I have two buttons (as expected), speaker and Sonos. 
I broke up alle the groups. So every speaker should react independently. Right?
As soon as I press the speaker Service button from the bathroom the group is recreated. And when I press the bedroom speaker service button the status of the button is immediately set to off again. 
I think this is a strange behavior and I can't manage to set the volume level as I want to.

**Comment by ebaauw** [comment]
> So you think the setup should work as expected?

From the log excerpt homebridge-zp works as intended.  Check the Sonos app to understand how group volume behaves.  Whether you expect that, is a different story.  Please read the README: the _Sonos_ service is linked to the zone group; the _Speaker_ service is linked to the zone.

> As soon as I press the speaker Service button from the bathroom the group is recreated.

Yes, by design.  Turning the_Sonos_ service on/off is for play/pause; turning the _Speaker_ service on/off is for grouping/ungrouping.

**Comment by keycized** [comment]
This is quite confusing. How does the, for example, bathroom speaker service knows that it should create a group with the bedroom speaker. Just the the bathroom speaker is on and the bedroom speaker is off. 
The other way around it doesn't work. Switching on the bedroom speaker and pressing the speaker service button nothing happen. except, that the service just switches off again immediately.
Please excuse my asking.

**Comment by keycized** [comment]
See here the debug log:
[homebridge_debug.log](https://github.com/ebaauw/homebridge-zp/files/4003050/homebridge_debug.log)

**Comment by ebaauw** [comment]
>  How does the, for example, bathroom speaker service knows that it should create a group with the bedroom speaker.

There's a custom characteristic, _Sonos Coordinator_ which indicates which zone is the intended group coordinator.  Apple's Home app doesn't show custom characteristics, so you need to use another HomeKit app to view and set it.  If you create a scene from Eve and include this characteristic, you can still recall the scene from Home.

> The other way around it doesn't work.

Because you cannot group the designated coordinator.

> Please excuse my asking.

That's OK.  I never came around to doing a clean writeup of this in the Wiki.  The details are described here: https://github.com/ebaauw/homebridge-zp/issues/94#issuecomment-516969748;

**Comment by keycized** [comment]
So far I understand the concept with the groups and coordinator. This is also how I set up the scene in Eve, which recreates the bathroom/bedroom group every day. 
In the example I mentioned earlier, I meant that I broke up the group in the Sonos app, and then I didn't use an Eve or Home Scene to turn on the Bathroom Speaker, but I used the standard Home button. In that moment, the group was also merged back together (Bathroom/Sleeping Room).
I don't have a scene where I make the bathroom speaker a coordinator. 
I notice that not all "Speaker" buttons react the same (I mean the "Speaker Service" buttons in the Home app). I can't use the "Speaker" button on one particular speaker. As soon as I turn it on, it is immediately switched off. 
I somehow have the impression that the system is out of sync. I already tried to remove the homebridge from the home app. Without success. 
Is there a way to reset homebridge? Does that even make sense?

**Comment by ebaauw** [comment]
> I don't have a scene where I make the bathroom speaker a coordinator.

Note that in Sonos, every zone group has one coordinator (even zone groups only consisting of a single zone).  homebridge-zp shows that as _Sonos Group_ in the _Sonos_ accessory.  homebridge-zp maintains one target coordinator, which it shows as _Sonos Coordinator_.  The Sonos system doesn't know this concept (you simply specify what group you want the zone to join); homebridge-zp simply retains the value, until it is changed (by setting the _Sonos Coordinator_ in another _Sonos_ accessory).  So if you "turn on" the _Speaker service, it will join the group of the previously set target coordinator.

> I can't use the "Speaker" button on one particular speaker. As soon as I turn it on, it is immediately switched off.

That's the _Speaker_ service for the target coordinator.  In order to make it join another zone's group, you need to set another zone as target coordinator.

> I somehow have the impression that the system is out of sync.

What system?
- The zone players vs homebridge-zp?  That would typically be the case when homebridge-zp no longer receives updates from the zone players (because the zone player no longer has a subscription from homebridge-zp).  Power cycling a zone player might cause this (although I try to handle this case), as might network interuptions.  Restarting homebridge should remedy this.
- HomeKit vs homebridge/homebridge-zp?  That would typically be caused by network issues between the HomeKit runtime (on your iDevice) and the HomeKit accessory (i.c. homebridge).  Note that HomeKit uses Bonjour (DNS-SD) to find the accessories, which does not work well with routers and switches that do IGMP snooping.  Switching off and on the Wifi on your iDevice and/or rebooting it should remedy this.  You can check with `netstat` whether each iDevice connects to homebridge, or run `DEBUG=* homebridge -D` to make homebridge log requests from the HomeKit runtime.

> I already tried to remove the homebridge from the home app. Without success.

That does nothing to the sync between homebridge-zp and the zone players and nothing to the network between HomeKit and homebridge.

> Is there a way to reset homebridge? Does that even make sense?

To re-initialise homebridge-zp (and all other plugins): Stop homebridge, delete `~/.homebridge/accessories/cachedAccessories` and restart homebridge.  You accessories will appear to HomeKit as new accessories, losing any assignments to HomeKit rooms, groups, scenes, and automations.  This will also lose the target coordinator; "turning on" _Speaker_ services might fail, until you set a new target coordinator.

To factory reset homebridge itself: Stop homebridge, delete everything in `~/.homebridge/persist` and in `~/.homebridge/accessories` and restart homebridge.  You need to re-add homebridge to HomeKit after that.  Only do this as a last resort, i.e. when HomeKit no longer communicates with homebridge at all, even after waiting several hours.
