### ISSUE TITLE
Warning heartbeat and drift

### ISSUE THREAD

**Issue by tomsteenbakkers** [ebaauw/homebridge-zp#127]
During startup I get a lot of warning about heartbeat/drift. What does this warning mean and what can I do to remove these. 

After the homebridge is running Sonos is working like a charm. 

![CED322F3-DBE9-4010-9BD2-5524776CC80E](https://user-images.githubusercontent.com/24613800/75573511-4982f900-5a5d-11ea-866e-8a6255782138.jpeg)

**Comment by ebaauw** [comment]
It’s an indication that some code is blocking the NodeJS process, causing the heartbeat not to be triggered on the scheduled time.  I wouldn’t be too worried to see some of these warnings during homebridge startup, but 25 seconds is quite a lot, and this seems to be ~20 minutes after starting homebridge.  You might be using an ill-behaving plugin.

The `beat` is the heartbeat number since starting homebridge.  There’s one heartbeat every second, so effectively it’s the time in seconds since the heartbeat started (shortly after homebridge has started its HAP server).  The `drift` is the difference between expected trigger time and actual trigger time, in ms.  I think I issue the warning when it’s off by more than half a second.
