### ISSUE TITLE
Remove TV accessory input limit

### ISSUE THREAD

**Issue by Kienz** [ebaauw/homebridge-zp#135]
In the Home.app the TV accessory only shows 16 input sources (Sonos favorites). Remove these limit and adjust it to the HomeKit limit (96 or 97).

**Comment by ebaauw** [comment]
Note that each input source is a separate HomeKit service.  Next to these, the TV accessory has an _Accessory Information_ service, a _TV_ service, and a _TV Speaker_ service.  With a maximum of 99 services per accessory, there's room left for 96 _Input Source_ services.

Homebridge ZP reserves the first four and the last _Input Source_ services: group/ungroup, Airplay, LineIn, TV, and Sonos Chime.  So that leaves room for 91 favourites.

Note that Homebridge ZP creates the input sources statically on startup.  If configures them dynamically, as Sonos favourites are updated, enabling or disabling the source and changing its name.  I don't know how much overhead the disabled input sources cause.  Please let me know if you run into issues.  Maybe this should be a config.json parameter instead of a hard-coded constant.

**Comment by Kienz** [comment]
I think something is wrong after update to 1.0.28 - see screenshots.
But in the input sources only 16 are displayed - like before 1.0.28.

![image](https://user-images.githubusercontent.com/954545/80921996-5c29ef00-8d7a-11ea-81bf-775c603acd93.png)

![image](https://user-images.githubusercontent.com/954545/80922006-69df7480-8d7a-11ea-9e6f-0aaa24ebe79b.png)

![image](https://user-images.githubusercontent.com/954545/80922015-7368dc80-8d7a-11ea-92c6-2fa8e65144aa.png)

![image](https://user-images.githubusercontent.com/954545/80922026-8b406080-8d7a-11ea-8807-f41bee16352f.png)

![image](https://user-images.githubusercontent.com/954545/80922029-8f6c7e00-8d7a-11ea-90e8-1094dcbd347f.png)

**Comment by ebaauw** [comment]
Force-quit Home and restart it.

**Comment by Kienz** [comment]
Thanks! Solved.
