### ISSUE TITLE
Discover multiple Sonos systems on same network / select Sonos system to use with homebridge

### ISSUE THREAD

**Issue by fanfadrian** [ebaauw/homebridge-zp#153]
#### Issue

Thanks for the great plugin, I really appreciate your work!

I have two Sonos systems running on the same network. One with my main players for music listening and one with a speaker dedicated to play announcements and alarms (via node-sonos-http-api).

I didn't find a way to discover and expose both systems to Homebridge/Homekit. But this is not so important to me, because I only want to control the system with the main players. But, unfortunately again, homebridge-zp discovers and exposes the one that I don't want to control (the one used for node-sonos-http-api). Maybe this is because it discovers it first when scanning the network.

With node-sonos-http-api I can specify the Sonos HouseholdControlID to specify which system to use. Would that be possible? Or is discovering two systems on the same network the better approach? Both would solve my problem :)

Thanks in advance!

**Comment by ebaauw** [comment]
Homebridge ZP currently doesn't handle households.  That's why I implemented the trick to register Homebridge ZP twice for a split S2 vs S1 setup.  It's on my to-do list to change this, and handle multiple households structurally, but it's low on the prio list.  That might change if I win the lottery, but currently I don't have enough rooms to hit the 32 zone player limit.

Not sure I want to expose end users to household IDs, but maybe I could make it possible to specify the associated zone player (as `RINCON_...` ID, so it doesn't need a fixed IP address) in config.json.

> Maybe this is because it discovers it first when scanning the network.

Yes, it's the first to respond to the UPnP search.  I'm afraid the only current workaround would be disconnecting the "unwanted" zone player from the network, or powering it down, when starting Homebridge.  The bastards at Sonos disabled remote shutdown/reboot of the zone players, so there's nothing I can do.

**Comment by ebaauw** [comment]
Could you please try beta v1.4.0-0.  This version handles multiple households.  It logs the topology per household, and maintains an associated zone player as well as _Sonos Coordinator_ per household.  Note that favourites are per household, and you can only group a zone to another zone within the same household.  The inputs to the TV accessories should reflect that.

Consequently, the ZPS1 platform is no longer exposed and the `forceS2` config.json key is silently ignored.  I'll remove this in the next version.

In my testing the beta seems to work properly, but I only have an S2 household with 11 zone players and an S1 household with a single zone player.

**Comment by ebaauw** [comment]
In v1.4.0.
