### ISSUE TITLE
Can’t change name

### ISSUE THREAD

**Issue by tomsteenbakkers** [ebaauw/homebridge-zp#155]
I have used the plugin now for several months and I'm very happy with it. I have 3 Sonos Play1 devices. 1 in the `Lounge` and 2 (stereo pair) in the `Woonkamer`.

When I change the name of the 2 in the `Woonkamer` to `Sonos`, after a few seconds the names changes to `Living Room Sonos`. 

The name `Living Room` is also not mentioned in the Sonos App and also not in the log of Homebridge during startup.

Any idea how I can solve this?

**Comment by ebaauw** [comment]
Are you on v1.1.3 of Homebridge ZP?

**Comment by tomsteenbakkers** [comment]
> Are you on v1.1.3 of Homebridge ZP?

1.1.3

**Comment by ebaauw** [comment]
Where are you changing the name?  In the Sonos app?  From HomeKit?  Using Home?  Eve?  Are you changing the service name or the accessory name?

**Comment by tomsteenbakkers** [comment]
I have tried in the Home App and the Eve app. Also tried to set the configuration option `Name Scheme` but when the name is changed, after a few seconds it reverts back.

Changing the name of the accessory. When renaming `Living Room Sonos` to `Sonos` (see picture below) it reverts back to `Living Room Sonos`


![image](https://user-images.githubusercontent.com/24613800/101397710-54f92f80-38cd-11eb-96d3-43c31855d397.png)

**Comment by ebaauw** [comment]
The good news: I can reproduce the issue.  The bad news: I have no clue what's causing it.  It seems to be a residual setting in HomeKit.  I tried to add a _Configured Name_ characteristic in the previous version, to see if I could sync the HomeKit name with the Sonos name, but that didn't work out too well.  I removed _Configured Name_ in 1.1.3 (1.1.2 actually) and as far as I can tell there's no traces of it in the plugin code, nor in `cachedAccessories`.  It would seem however, that HomeKit still has it, and since it receives no confirmation when you change it from HomeKit, it reverts the service name to its previous value.

> What I do not understand where the name Living Room comes from.

I would think that was the last name of the service (and the value of _Configured Name_) under the previous version of Homebridge ZP.

> Changing the name of the accessory.

No, that's the service name; the Home app is lying through its teeth.

> Also removed the accessory from the cache using HomeBridge UI.

Did it revert to the default room (the room with Homebridge in it)?  If not, it wasn't removed from HomeKit.

**Comment by lukenukemmp3** [comment]
I also have the problem that renaming in Home App doesn't work. I tried to uninstall the plugin, but the speakers stoll showed up in the home app, so I can't remove them and add them again.

**Comment by ebaauw** [comment]
Restart Homebridge after uninstalling the plugin and removing the section from config.json to delete the accessories exposed by Homebridge ZP.

**Comment by lukenukemmp3** [comment]
I have done both, but the accessories were still there.

**Comment by ebaauw** [comment]
Better contact hoobs support then.  Homebridge should delete the orphaned accessories, except when started with `-K`.

**Comment by lukenukemmp3** [comment]
Thank you, I will. The problem is also reported on reddit, there are many users with this issue.

**Comment by ebaauw** [comment]
Which issue: not being able to _remove_ accessories or not being able to _rename_ accessories?

**Comment by lukenukemmp3** [comment]
Excuse me, I meant the _remove_ issue.
The _rename_ issue caused that I tried to remove the speakers.

**Comment by tomsteenbakkers** [comment]
This how i fixed it:
- Create backup of config.json using Homebridge Config UI
- Removed plugin
- Removed section in config.json
- Restart Homebridge without option -K
- Reinstall plugin homebridge-zp
- Restore backup of config.json using Homebridge Config UI
- Restart homebridge

**Comment by ebaauw** [comment]
Yes, the accessories need to be removed from HomeKit and then re-added as new accessories.  Alternatively, you can also achieve this by removing them from `cachedAccessories` though the Homebridge UI.
