### ISSUE TITLE
Independent volume control while in Group 

### ISSUE THREAD

**Issue by sabinlazar** [ebaauw/homebridge-zp#16]
Hello Erik. First of all thanks for developing this very useful plugin.
Secondly, I cannot seem to find a solution to configure it the way I want it to work. I will describe my setup in detail below.

My setup is comprised of 4 Sonos Play1 speakers and 4 Philips Motion Sensors. I created automation rules inside Apple home app and using the Hue Room lights for triggers: the sensors trigger the lights and the lights trigger the speakers. When the lights turn off, the volume of the speaker is set to 0. I use this approach of turning the volume to 15% for on and to 0% for off to get rid of the delay existing when using the on/off (play/pause) speaker setup. Most of the time all the speakers use the same radio station.
The problem I am facing is that by controlling each zone independently, the speakers audio source is not synchronised. If i use sonos groups i cannot control the volume of each zone independently from the automation. It works if I do it manually on each speaker but when I try to automate it or control the volume of the individual speaker from Home app it affects the group volume, even if I only modify the speaker volume and not the group.

The scenario that would work is: all 4 sonos speakers in one group; automations control individual speaker (zone) volume. 
I tried setting this up but modifying one speaker/zone volume affects the whole group volume. Setting one zone to 0 sets all the speakers in the group to 0 even if the Home App show a different volume for the Group/Speakers accessory. 

Is this desired scenario possible? Am I missing something?

This is the config I use now but stoped using the Speakers accessory for automations because of the behaviour described above.

 "platforms": [
    {
      "platform": "ZP",
      "name": "ZP",
      "service": "speaker",
      "brightness": true,
      "speakers": true
    }
  ]

Many thanks!

**Comment by ebaauw** [comment]
> My setup is comprised of 4 Sonos Play1 speakers and 4 Philips Motion Sensors.

That resembles my setup: multiple rooms with Sonos players and Hue Motion sensors and lights.  When I enter a room, the lights turn on (when it's dark) and the music starts playing.  When I leave the room, the lights and music turn off.

> I created automation rules inside Apple home app and using the Hue Room lights for triggers

You might want to check out [my homebridge plugin for the Philips Hue](https://github.com/ebaauw/homebridge-hue): it exposes the Hue motion sensors to HomeKit, so you don't have to use a light as trigger (and the lights can remain off when there's enough natural light).

> I use this approach of turning the volume to 15% for on and to 0% for off...

You might want to use `Mute` instead.  It's less confusing, as the group only goes on mute when all member zones are muted.  
I actually use the _Speakers_ `Power` (on/off) characteristic in my HomeKit automations, to have the Sonos join/leave the group instead of adjusting the volume.

> ...to get rid of the delay existing when using the on/off (play/pause) speaker setup.

Do you mean the delay in the Sonos connecting to (and buffering) the audio source?  That's probably less of an issue when you make the zone join the group of another zone already playing the radio station.

> by controlling each zone independently, the speakers audio source is not synchronised

As far as I know, grouping zones is the only way to have music synchronised across multiple zones.

> but when I try to automate it or control the volume of the individual speaker from Home app it affects the group volume

Yes, that's how Sonos works: the group volume is like the average of the volumes of the member zones.  The volume of the other member zones shouldn't change, though, when adjusting the volume of a single member zone.  You see the same behaviour in the Sonos app: when adjusting the volume of a single zone in a group, the group volume changes as well, but the other zones remain unchanged.

> Is this desired scenario possible?

Yes.

> Am I missing something?

Please note that the `Volume` (and `Mute`) of the _Sonos_ services are linked to the group volume and mute; the `Volume` (and `Mute`) of the _Speakers_ services are linked to the individual zones.  
So when you set the _Speakers_ volume of one member zone, the _Sonos_ volume of all group member zones changes, but the _Speakers_ volume of the other group member zones is unchanged.  
When you set the _Sonos_ volume of one member zone, the _Sonos_ volume of the other member zones changes (because these all point to the same group volume) and the _Speakers_ volume of all member zones changes (because of the change to the group volume).  
It's confusing, I know.  Best ignore the _Sonos_ service `Volume` and only look at the _Speakers_ service `Volume`.

**Comment by sabinlazar** [comment]
Thank you very much Erik for the detailed explanations and suggestions! I use the Speakers service and mute instead of Sonos services and everything works as expected now.

Many, many thanks!
