### ISSUE TITLE
Enhancement: Ability to toggle individual or group volume for volume change parameter, and ability to cycle through/select favorites

### ISSUE THREAD

**Issue by rfiorentino1** [ebaauw/homebridge-zp#184]
#### Issue
Note: I've been using the Eve app to control/automate most of ZP
1. In the configuration settings, is there a way to create a true/false for allowing the "volume change" parameter to control the individual speaker while in a group? I know you can add a speaker service to do this, but that doesn't seem to allow me to automate the increase or decrease of volume from where it currently is, just sets the volume to a specific level. Please let me know if I need to clarify this further.
2. It looks like this plugin can allow you to change the source of a zone, or start a favorite, etc, however I can't seem to find where/how to do that? Maybe I'm just misunderstanding something, or didn't configure correctly?
Thank you so much for creating/maintaining this plugin, it's incredible, and opens up a whole host of amazing automation. I've been using it for more granular control of Pico Remotes with Sonos.

**Comment by ebaauw** [comment]
Ad 1.  Use the _Volume Change_ characteristic on the speaker service.  In my setup, I created HomeKit scenes in Eve for Volume Up and Volume Down, setting _Volume Change_ to 1 or -1 respectively.  Then in Home, I assigned these scenes to the Up and Down buttons of a Trådfri remote.  I actually use additional scenes to change the volume by 10 or -10 for long press.
Ad 2.  If you set `tv` in config.json, Homebridge ZP exposes a standalone Television accessory per zone.  The favourites are exposed as inputs.  Unfortunately, this accessory appears only in Home.  Because of this, the sonos service also carries _Active Identifier_, which matches the input number from the Television accessory.  Using _Input Change_ allows you to cycle through the inputs.  I defined HomeKit scenes for this in Eve, and assigned them to long pressing the Previous and Next buttons on the Trådfri remote.  For short press, I use _Track Change_.

**Comment by korbinio** [comment]
For me the favorites are rebuilt every time I restart homebridge. Therefore disabling "Sonos Chime" manually in the favorites is not really an option. Since I don't use alarms in Sonos at all: Is there an option to completely disable the Chime channel? Or an other workaround to flip through my playlists without Sonos chime breaking it?

**Comment by korbinio** [comment]
@ebaauw: Would it be possible to implement the option to disable Sonos Chime completly? Or how do you handle this issue? I would imagine that I am not the only one that is trying to cycle through all Favorites and does not want to hear the Sonos alarm...

**Comment by ebaauw** [comment]
Tbh, I mostly listen to the same radio station and use the Sonos app, Spotify, or Airplay when I’m in the mood for something else.  I do want to persist the favourites sometime, but that’s low on my prio list.   As I said, I’m not too sure about having no inputs at all, so the chime acts as safety net.  Maybe I can disable it when re-creating the input list, when there’s other inputs.  That should be a relative low-key change.

**Comment by korbinio** [comment]
> [...] Maybe I can disable it on re-creating the input list, when there’s other inputs. That should be a relative low-key change.

This would be the perfect solution from my point of view :)

**Comment by ebaauw** [comment]
In v1.4.14.

**Comment by rfiorentino1** [comment]
This works beautifully, thank you!

**Comment by rfiorentino1** [comment]
After updating to 1.4.14, The chime is still in my favorites when I browse through them, even though there are other inputs/favorites there already.

**Comment by ebaauw** [comment]
When I tested this on my test Home (with only a dozen accessories), it worked, i.e. the Chime was no longer checked in the settings.  However, it doesn't seem to be working on my production Home either, with well over 200 accessories.  I've seen before that HomeKit configuration changes are lost intermittently, during syncing over iCloud of those changes to all your Apple devices.  Especially with larger configurations and many changes in short succession.  Never been able to put my finger on it.  And HomeKit seems to treat the changes to the inputs more like configuration changes than state changes, even though it's only some characteristic values that change.

**Comment by ebaauw** [comment]
Could you try beta v1.4.15-0?  That seems to work on my production Home:
- I added a guard not to run into an infinite loop when no inputs are enabled.
- Turned out I created the Sonos Chime input as visible (enabled), turning it invisible (disabling it) immediately afterwards.  Too many config changes in short succession.  Now creating the input as invisible to start with.
- Skip over Sonos Chime with _Input Change_, irrespective of whether the input is enabled or not.  I might remove this safety net in future, when the previous point turns to be working out.

**Comment by rfiorentino1** [comment]
Awesome, this works perfectly now, thank you. Maybe another potential option at some point would be to make inputs that aren't favorites (line in, TV, etc.) bullion values/checkboxes in the UI so that users could choose what they want in that list. Also, slight side note, there are one or two times where I trigger an input change to cycle through favorites, and nothing happens. The last favorite continues to play, even though the active identifier changes/input changes, almost to an empty slot. Not a big deal at all, but wanted to let you know. If that's the biggest problem I have, today is a great day :)
Thank you again.
