### ISSUE TITLE
Input Enhancement 

### ISSUE THREAD

**Issue by justinshuls** [ebaauw/homebridge-zp#203]
#### Issue

Can’t resume airplay audio from inout menu, say you switch to tv audio but than want to go back to the airplay audio (s2 devices)

additional would be lovely to just be able to use input feature without all the other accessories, maybe a whitelist?

thanks for the cool plugin!

#### Log Messages

```
```

**Comment by ebaauw** [comment]
> Can’t resume airplay audio from inout menu, say you switch to tv audio but than want to go back to the airplay audio (s2 devices)

That’s how AirPlay works: rather than the zone player initiating an outgoing connection to the audio source, the source initiates a connection to the speaker.  You cannot initiate AirPlay from the Sonos app either.

> additional would be lovely to just be able to use input feature without all the other accessories, maybe a whitelist?

Not sure what you mean?  If you don’t want the _Sonos_ accessories, run Homebridge ZP in a child bridge, and don’t pair that child bridge with HomeKit.  If you don’t want TV accessories for some zone players, don’t pair those TV accessories with HomeKit.  Internally, Homebridge ZP needs the _Sonos_ accessories for all zone players in a household.
