### ISSUE TITLE
added speaker get removed from scenes after time

### ISSUE THREAD

**Issue by Somberland** [ebaauw/homebridge-zp#22]
I'm quite not sure why this happens (maybe some id changes or so?) but my speakers get removed from time to time from my homekit-scenes (leave home, etc.)

Am I the only one with this behaviour?

**Comment by ebaauw** [comment]
Typically this happens when homebridge restarts, and homebridge-zp doesn't find all your speakers.  HomeKit then removes the missing speaker.  You restart homebridge again, homebridge-zp finds the speaker this time, and HomeKit creates a new speaker, which looks the same, but has lost the room and scene assignments.

The structural solution is for homebridge-zp to remember the speakers it saw previously, and expose these these already to HomeKit on restart, before finding them.  However that requires dynamic platform accessories (issue #1), which is a huge change for me.  
Until then, you might want to be sure homebridge is started only when the network is up, and when all your Sonos speakers are visible.  You might want to give homebridge-zp some more time to find the speaker, by setting `searchTimeout` in config.json, see **Configuration** in the Readme.
