### ISSUE TITLE
Enable / Disable Status Light on Sonos

### ISSUE THREAD

**Issue by pauloruberto** [ebaauw/homebridge-zp#28]
It would be great if we could get control of the status light on the top of the Sonos. I have one in my bedroom and would love to automate the disable of that light when going to sleep!

**Comment by ebaauw** [comment]
Technically, that’s easy.  Functionally, would you want an additional `Lightbulb` service with an `On` characteristic, or an additional (custom) characteristic to the _Speaker_ service?

**Comment by pauloruberto** [comment]
I think that a custom characteristic for the speaker service might be the best option, just to keep everything more organized and grouped together.

**Comment by ebaauw** [comment]
You do realise that, in that case, you wouldn't be able to control the status light from Apple's Home app, nor from Siri?  You would be able to create a scene in Eve (or another HomeKit app) that includes the status light characteristic, and recall that scene from Apple's Home, Siri, or a HomeKit automation.

**Comment by pauloruberto** [comment]
Hmm, that is true. Perhaps exposing it as an additional switch or lightbulb would be a better idea, as Siri control would be nice to have.

**Comment by ebaauw** [comment]
Added in v0.2.26.  Set `"leds": true` in config.json to get an additional _Lightbulb_ service, _Room_`Sonos LED` per Sonos accessory.

Note that the LED state isn't updated automatically - you need to refresh the data from your HomeKit app.  
The Sonos speakers don't issue events when the LED state is changed.  You can verify that in the Sonos app: when changing the LED state from one instance of the app, the other instance doesn't immediately reflect this.  You need to close and re-open the _Room settings_ before you see the new state.  
I could workaround this by polling each zone for the LED state, but homebridge-zp doesn't use polling at all (because all the other updates are received through events).  Also it seems a bit overkill to poll the speakers just for the LED state.  So instead, I implemented the same functionality in HomeKit: you need to refresh the screen for the LED state to be updated.  Technically, homebridge-zp only updates the LED state on reading the characteristic, instead of pushing changes to it.

Please let me know what you think of this.
