### ISSUE TITLE
Running with openvpn

### ISSUE THREAD

**Issue by itskeKs** [ebaauw/homebridge-zp#30]
Hey great plugin. Works as it should.

Only problem i am running into: I have an vpn connection to an external vpn with my raspberry pi running. when the vpn connection is enabled then homebridge does not discover any sonos players. when i disable it then it discovers the players and it still works when i reconnect to the vpn server. i tried binding homebridge-zp to the local iop but it did not help. i also added ip routes but still not working. binding and passing the port through iptables did also not help.

any ideas?!

**Comment by ebaauw** [comment]
Just so I understand correctly, the Raspberry and the Sonos players are on the same side of the VPN, the Raspberry just acts as VPN server for remote clients (or is a VPN client to a remote VPN server)?  This means that when the VPN is active, the Raspberry has two different IP addresses.

On startup, homebridge-zp retrieves the IP address of the local machine.  When subscribing to the Sonos players to receive state change notifications, homebridge-zp specifies its own IP address in the callback URL.

With help of Murphy, it (or rather the network core of NodeJS) homebridge-zp probably picks the wrong one when the VPN is active.  You can verify that running `homebridge -D`, see https://github.com/ebaauw/homebridge-zp#troubleshooting.  Because of this, it wouldn't receive any notifications from any Sonos player.  You can force the right IP address in config.json, using the `host` key, see https://github.com/ebaauw/homebridge-zp#configuration.

Not sure if that's actually the issue you're facing.  Before setting up the subscriptions, homebridge-zp need to discover the Sonos players.  This is done through UPnP.  I haven't seen any issues with this on multi-homed hosts, but I'm not sure there aren't any.  I still use the `sonos` library for discovery.  If specifying `host` in config.json doesn't help, could you please run `homebridge -D` (when the VPN is active) and attach (not: cut/paste) the debug out here, see https://github.com/ebaauw/homebridge-hue#debug-log-file.
