### ISSUE TITLE
Airplay 2

### ISSUE THREAD

**Issue by Tommrodrigues** [ebaauw/homebridge-zp#33]
Hey there,

I really appreciate the work you've put into this plugin and it's made a real difference being able to automate my Sonos speakers! My current setup is simply four Play:1 s but I'm looking to get an outdoor speaker system set up. As a result, I've been waiting for Airplay 2 so that I can use an AirPort Express as the receiver for this new system. I was original hoping that Sonos would release AirPlay 2 compatibility with all of their products but it is clear from their blog post [here](https://blog.sonos.com/en/airplay2-coming/) that this is not the case. As a result I think I will go with the option of  buying a Play:5 or another Airplay 2 compatible speaker and using that as the hub for my incompatible speakers as mentioned in their post so that I can stream audio to my Sonos and also outdoors. 

Following this, there were a number of questions I still had which I was hoping you'd be able to give me some guidance with. The first question I admittedly am not sure whether you'll be able to help with but hey it's worth a shot! I was wondering whether in theory it would be possible to create some sort of server that could run, similar to [node-sonos-http-api](https://github.com/jishi/node-sonos-http-api) which would expose the previously non AirPlay 2 compatible Play:1s as Airplay 2 speakers both within the Home app and more importantly for multi-room audio without the need to buy the Play:5 or such like as this would be ideal.

My next question is one I'm sure you'll know the answer to. If I were to buy a Play:5, I assume that it would appear in the Home app as a speaker without the use of your plugin. However, if I were to still use your plugin for the rest of my speakers, would this then make a duplicate of this new speaker inside the home app? If so, is there a way for homebridge-zp to ignore certain speakers on a network?

My final question is more of an aesthetic concern than a practical one. I am currently showing the exposed Sonos speakers as fans in the home app as this is the only way to have volume control within the app. When AirPlay 2 is released, will the "speaker" option work rather than having to show them as fans?

Thank you in advance for your help!
Kind regards,
Tom

**Comment by ebaauw** [comment]
> I was wondering whether in theory it would be possible to create some sort of server [...] which would expose the previously non AirPlay 2 compatible Play:1s as Airplay 2 speakers both within the Home app

In theory yes, but I don't think they've yet reverse engineered the Airplay 2 protocol.  The abandoned airsonos project turns your Sonos zones into Airplay 1 speakers, see https://github.com/ebaauw/homebridge-zp/issues/21#issuecomment-312038907.  I'm half considering integrating that into homebridge-zp.

> If I were to buy a Play:5, I assume that it would appear in the Home app as a speaker without the use of your plugin.

It would appear in the Home app, but not in any other HomeKit apps.  Airplay 2 is a different protocol than HAP (what HomeKit accessories talk).

> is there a way for homebridge-zp to ignore certain speakers on a network?

No.  
The way I read the (somewhat vague) blog, is that you can group other zones with the new (touch control) player, so that the Airplay 2 audio is played in multiple zones.  I'm afraid you'd only see a single Airplay 2 speaker for your entire Sonos installation and you won't be able to control multiple rooms using Airplay 2.  You'd still use need to use homebridge-zp for that, incl. the new Airplay 2 speaker as group coordinator.  
I currently have a Sonos Connect hooked up to my mac mini server.  Using Airfoil, the server exposes itself as an Airplay speaker, playing to the line-out.  I configured the Connect to autoplay on line-in.  Effectively, it acts as an Airplay 1 hub, allowing me to stream music from any Apple device to my entire home.

> When AirPlay 2 is released, will the "speaker" option work rather than having to show them as fans?

No.  As said before, Home doesn't use HAP to communicate with Airplay 2 speakers.

**Comment by Tommrodrigues** [comment]
Thank you for your quick response!

It's a shame that the Airsonos project has been abandoned. I have it running on an old iMac at the moment simply so that I can Airplay music from YouTube to my Sonos speakers. But of course, Airsonos is just Airplay 1 so wouldn't work for playing music both through my Sonos speakers and the outdoor ones (unless I use iTunes on Mac). Any idea on when or even if someone would reverse engineer the AirPlay 2 protocol and release a server similar to Airsonos? (By the way I think it would be really cool if you did manage to integrate it into homebridge-zp!)

Yeah it's a shame all the Sonos play:1s would just appear as one Airplay 2 speaker but it looks like I might have to settle for just that.

> I currently have a Sonos Connect hooked up to my mac mini server. Using Airfoil, the server exposes itself as an Airplay speaker, playing to the line-out. I configured the Connect to autoplay on line-in. Effectively, it acts as an Airplay 1 hub, allowing me to stream music from any Apple device to my entire home.

I was considering doing similar thing but instead running mikebrady's [shairport-sync](https://github.com/mikebrady/shairport-sync/) on a headless Raspberry Pi and using that so stream the music to my outdoor speakers but I would of course need to wait for Airplay 2 to be reverse engineered and made into a similar project for the Raspberry Pi so instead I think I'm going to go for the AirPort Express option as it will apparently support AirPlay 2 as said [here](http://www.idownloadblog.com/2018/04/04/airport-express-will-apparently-gain-airplay-2-speaker-support/).

> No. As said before, Home doesn't use HAP to communicate with Airplay 2 speakers.

It's a shame they won't appear as a speaker service when AirPlay 2 is released but not to worry as it's no big deal! Any idea on whether this could possibly be fixed in the future?

Kind Regards,
Tom

**Comment by ebaauw** [comment]
> Airsonos is just Airplay 1 so wouldn't work for playing music both through my Sonos speakers and the outdoor ones
> I was considering doing similar thing but instead running mikebrady's shairport-sync on a headless Raspberry Pi and using that so stream the music to my outdoor speakers but I would of course need to wait for Airplay 2 to be reverse engineered and made into a similar project for the Raspberry Pi

You might want to check out [Airfoil](https://rogueamoeba.com/airfoil/).  It exposes itself as an Airplay speaker, forwarding the audio streams synchronised to a number of (Airplay or other) speakers.  It includes Airfoil Satellite, which turns you computer or iOS device into an Airplay speaker (I suppose similar to shairport-sync).  
Before Sonos, I used Airfoil to stream music multi-room, to an Airport Express and to two B&O Playmaker devices, using homebridge-music to expose this to HomeKit.  The Playmaker is basically an Airport Express, with a better DAC, and with a B&O powerlink (speaker) connection.  Didn't work as reliable as Sonos, though, and never got it working reliably over WiFi.

> Any idea on when or even if someone would reverse engineer the AirPlay 2 protocol and release a server similar to Airsonos?

Not a clue.  I won't be doing that (I hardly understand the Airsonos code).

>  I'm going to go for the AirPort Express option as it will apparently support AirPlay 2 as said here.

This almost sounds too good to be true.  It would require a firmware update of the Airport Express, which Apple discontinued.  I have one lying around (and even an older model), so I'll be monitoring this.  
Even then, it seems like Apple has delayed multiroom support for Airplay 2 once again.  The latest iOS and tvOS betas include Airplay 2, but without multi room support.

> It's a shame they won't appear as a speaker service

The problem is not with the _Speaker_ service, in fact, with the right config.json setting, homebridge-zp and homebridge-music already expose the _Speaker_ service.  The problem is that Apple's Home app and Siri don't support the Speaker service (other than as part of a video doorbell).  The do expose Airplay 2 speakers, but that has got nothing to do with HomeKit (and won't work with other HomeKit apps, unless they decide to implement an Airplay 2 client as well).
