### ISSUE TITLE
Unpredictable grouping behaviour in scenes

### ISSUE THREAD

**Issue by Garywoo** [ebaauw/homebridge-zp#40]
I have noticed some unpredictability when it comes to grouping speakers using scenes. For example, I have an automation that runs at 6:00 each morning to ungroup all speakers (all speakers: power = `false`), then another automation at 6:01 that groups two speakers together. Occasionally, another previously grouped speaker (before the 6:00 ungrouping) will end up in the group. 

I ran some repeated tests and was sometimes able to replicate the issue I was seeing. Looking at the homebridge logs, I saw the following: 

```
0|homebrid | [2018-8-2 19:12:17] [ZP] Bathroom Sonos: power (group membership) changed from true to false
0|homebrid | [2018-8-2 19:12:17] [ZP] Kitchen Sonos: platform coordinator
0|homebrid | [2018-8-2 19:12:17] [ZP] Kitchen Sonos: power (group membership) changed from true to false
0|homebrid | [2018-8-2 19:12:25] [ZP] Kitchen Sonos: coordinator for group Kitchen
0|homebrid | [2018-8-2 19:12:30] [ZP] Bathroom Sonos: platform coordinator
0|homebrid | [2018-8-2 19:12:30] [ZP] Bathroom Sonos: coordinator for group Bathroom
...
...
...
0|homebrid | [2018-8-2 19:12:52] [ZP] Kitchen Sonos: coordinator for group Kitchen
0|homebrid | [2018-8-2 19:16:38] [ZP] Bathroom Sonos: power (group membership) changed from true to false
```
In this example, I manually performed the "Ungroup all" scene twice. Once at 19:12:17 and again at 19:16:38. 
I repeated the scene here because I noticed that the Bathroom speaker still had the power state `true` while all the rest of the speakers were `false`, after performing the scene. The Bathroom should have been `false`, as reported in the logs at 19:12:17, but it was not. There is no mention of the speaker power state changing back to `true` between the two `Bathroom Sonos: power (group membership) changed from true to false` logs.

I believe this odd behaviour where the power was state was not remaining `false` is why I was seeing additional speakers in my scene created groups.

**Comment by ebaauw** [comment]
Whether or not a (coordinator) zone (incl. the member zones in the same group) is playing is reflected in the _On_ characteristic of the  _Sonos_ service.  The _On_ characteristic of the _Speaker_ service indicates whether the zone is member of a group (or designated to become the group coordinator).

homebridge-zp designates one zone as “platform coordinator”.  On startup, this will be the group coordinator in case there is a group, or the coordinator of one of the groups (randomly) in case there’s multiple groups.  If there’s no group on startup, the zone corresponding to the first _Speaker_ service to be switched on will become the platform coordinator (even though no group is yet created).  Note that Sonos doesn’t know the concept of “platform coordinator”, only group coordinator.  Also note that Sonos allows for multiple groups, but homebridge-zp can only add zones to the one designated coordinator.

I find that sometimes homebridge-zp and Sonos get out of sync, and homebridge-zp’s platform coordinator is actually a member of another group.  This will result in UPnP 500 errors when trying to group another player.  This happens when grouping/ungrouping zones from the Sonos app, or when automatically ungrouping when switching to TV or line-in.

From you log excerpt, I cannot determine what’s happening in your case.  Could you please attach a full debug log (see 
https://github.com/ebaauw/homebridge-hue#debug-log-file), and screenshots of your scenes?

**Comment by Garywoo** [comment]
Thanks for the detailed response @ebaauw.

I ended up recreating the automation and scene from scratch while adding another speaker to my setup. Since doing this I have not yet seen the same problematic behaviour that I reported above, and currently everything is working reliably as expected.

If the issue does reoccur, I will do as you ask and capture the debug logs.

**Comment by ebaauw** [comment]
OK, I'll close this one for now.  Please re-open if the issue re-occurs.

**Comment by ebaauw** [comment]
Thanks for the log, this really helps.

After activating the _Ungroup_ scene, did you check wether all the speaker services were off?  I suspect the _My Room_ speaker was still on.  From the log, the Sonos zoneplayers cannot handle the ungroup commands quickly enough and consequently confuse homebridge-zp.  The turning off of the _Kitchen Speaker_ is handled before _My Room_ and _Bathroom_ have left the group, so homebridge-zp assigns _My Room_ to inherit the group, instead of disbandoning the group.
> [1/4/2019, 8:55:53 PM] [ZP] Kitchen Sonos: leave Kitchen Sonos to My Room 

This will be a tough nut to crack.  homebridge-zp would have to throttle the ungroup commands and only send the next command after it has received (and handled) the GroupManagement event from the previous command.  The current design of homebridge-zp handles commands and events independently per zoneplayer and offers no central point where this throttling can be implemented.  I don’t think delaying the callback to HomeKit until the GroupManagement event has been received (effectively blocking the HomeKit app) will help, as the updates are sent in parallel when activating a HomeKit scene.

As a workaround, you could try and activate the _Ungroup_ scene twice, a couple of seconds apart.
