### ISSUE TITLE
Airplay 2 still crashes

### ISSUE THREAD

**Issue by codepeon** [ebaauw/homebridge-zp#43]
Airplay 2 still crashes when starting a stream

I suggest changing
https://github.com/ebaauw/homebridge-zp/blob/7bd812052b16a648824f8be95ccfa2992151b250/lib/ZPAccessory.js#L336
to something more like
`if (item.res != null && item.res[0] != null && item.res[0]._) {`

**Comment by ebaauw** [comment]
Sorry about that.  Could you please try v0.2.31?

Also added an additional debug message to dump the json version of the CurrentTrackMetaData.  I get cross-eyed trying to read XML.

Note to self: should really `try`/`catch` the whole event handling (cf. homebridge-hue), so homebridge won't crash.  That's gonna be a bitch, because of all the callback functions.  Might be the trigger to move to v1.x of the `sonos` package, with `async` functions.

**Comment by codepeon** [comment]
What works. Thanks
