### ISSUE TITLE
2 speaker (Play:1 & One) dead

### ISSUE THREAD

**Issue by CheukFaiho** [ebaauw/homebridge-zp#60]
When I installed homebridge-zp, it work well in a few days ago. But one day the Home app show me the plugin is 'No response', and no longer my 2 speaker (Play:1 & One) were dead one after another after. When I plug in the power cord into the Sonos, they're nothing happened and power lamp isn't on.

I checked the power cord and it's perfectly OK. After that I google it but find nothing, so I have to connect the Sonos service team and repair it. Because I bought the Play:1 when I travel to UK and I live in China, I may have to pay a lot of money for repairs.

So I want to know, have this happened before?Will it be caused by this plugin?

**Comment by ebaauw** [comment]
I’ve never heard of this before. Afaik, homebridge-zp doesn’t do anything different from the Sonos app.

Are you sure the speakers are dead, not just the control from HomeKit?  _No response_ typically is caused by the connection between HomeKit and homebridge being lost.  Also note that you might need to restart homebridge after a Sonos zone player reboots, especially when it receives a new IP address.  What does the Sonos app report?

**Comment by ebaauw** [comment]
Could be.  To check network problem vs hardware problem:
- power down router 2;
- connect the Sonos to router 1 by wire (I take it router 1 runs a dhcp server);
- power cycle router 1, power up the Sonos;
- connect your phone  to router 1 over wifi;
- see if you can control the Sonos from the Sonos app.
