### ISSUE TITLE
Sonos Playbar hangs in Homekit when Playbar is on (Apple)TV sound

### ISSUE THREAD

**Issue by GuitarHer01** [ebaauw/homebridge-zp#61]
I have a setup with a Playbar in the livingroom and 2 Sonos Play:1's in other rooms.
Homebridge-zp works perfectly when playing music. It doesn't when in TV mode.

When the TV is turned on and the Playbar connects to it (Apple TV, Cablebox, etc), the Playbar is not responding in Homekit anymore. 
For the first minutes Homebridge shows "Power (play/pause) changed from true to false"  when the button is pressed and the homebridge icon shows an exclamationmark. Homekit stays only on ON and doesn't do anything anymore.
After a few minutes, Homekit shows " No reaction" and Homebridge is not showing activity.

As soon as the Playbar is changed from TV to music again, it is available immediately again.  

What did i do wrong here? Why is the Sonos Playbar not usable in TV mode in my setup?

**Comment by ebaauw** [comment]
> For the first minutes Homebridge shows "Power (play/pause) changed from true to false" when the button is pressed and the homebridge icon shows an exclamationmark. Homekit stays only on ON and doesn't do anything anymore.

The PlayBar doesn't accept Play nor Pause when on TV input.  The Sonos app dims the corresponding controls when this is the case, but HomeKit doesn't support this.  So instead I return an error to HomeKit, hence the exclamation mark.  You should still be able to control volume, mute, night sound and speech enhancement from HomeKit (although not from Apple's Home app).

While on TV input, the _On_ status in HomeKit reflects whether the PlayBar sees a signal on the optical input.  I recently introduced a boolean _TV_ characteristic (in addition to the _Track_ text characteristic), to be used in HomeKit automations, when the TV is turned off (or more precisely: is no longer sending sound to the PlayBar).  Since the input might drop for a little while when switching audio modes, _TV_ only turns off when _On_ has been off for 30 seconds.

> After a few minutes, Homekit shows " No reaction" and Homebridge is not showing activity.

You mean _No Response_?  I don't think this is related, but you might want to double check that homebridge hasn't crashed.  Typically this is due to network issues between you iDevice and homebridge, see the many issues on that.

**Comment by GuitarHer01** [comment]
Thanks for your answer!
So, if I understand it correctly, the fact that I cannot switch the Playbar to ON/OFF when it is in TV mode, cannot be solved. 

Second, the "No response" in Apple Homekit appears after a few minutes. 
At fist there is the exclamation mark on the Playbar button, after some minutes this changes to No response.
Homebridge than still works fine and the other Sonos devices can still be swtiched ON/OFF. 
Only after manually change the Playbar from TV to music mode again, the button in Homekit is usable again. 

This is a pitty, because the reason I wanted the Sonos in my Homekit, in stead of just using the Sonos App, is to use some automation with it. 
"Siri, goodnight", and the light are turned off, lower the temperature, and turn off all Sonos speakers. 

Now this only works while the Sonos Playbar is NOT in TV mode. Otherwise Homekit gives an error like "not all devices are responding"

**Comment by ebaauw** [comment]
So the _No Response_ is shown only for the PlayBar?  That’s not good.

I could try, instead of returning an error, simply to accept the off issued from HomeKit and reset the tile after half a second or so, but, indeed, there’s no way to pause, stop, or “turn off” the playbar when it’s on TV.

**Comment by ebaauw** [comment]
> how about muting/unmuting the PlayBar if the On/Off characteristic is changed and the source is the optical input? 

Too tricky, see also #12.

Also, I don't like providing a different experience than the Sonos app.  If you want to mute the PlayBar, do so using _Mute_ (use a HomeKit scene created in Eve or another app to do this from Apple's Home app or Siri).
