### ISSUE TITLE
Speaker volume after turning back on is too low

### ISSUE THREAD

**Issue by nzstaneo** [ebaauw/homebridge-zp#84]
Hi all,

Great plugin which has been working really well for me recently.

Have a small issue where if I turn off my bedroom Sonos one speaker via HomeKit using the switch service, upon power on again the volume is 1% and not the last state before turning off the speaker.

Funnily enough, my other speaker works perfectly when powered off and on(same volume state as when I powered off) 

Is this something I need to set in the Sonos app? My bedroom speaker is an airplay device whereas the other is a play1 if that makes any difference.

Thanks

**Comment by ebaauw** [comment]
I don’t know, apparently my zone players are too old and don’t support AirPlay.  I suppose the player could keep a different volume for different inputs, or change the volume when automatically switching inputs, similar to the PlayBar switching to TV input.

If you cannot find a corresponding setting in the Sonos app, you could create a HomeKit scene that turns the player on and sets the volume, and use that instead of the switch.  You need to create the scene in Eve, but after that, it can be recalled from Apple’s Home app.
