### ISSUE TITLE
Currently playing track stops when grouped

### ISSUE THREAD

**Issue by mylesagray** [ebaauw/homebridge-zp#94]
When grouping zones with a scene by turning the speaker attribute to on the currently playing track is stopped.

This is the case when the scene specified that sonos as coordinator and when it wasn’t coordinator.

I seem to be unable to reliably get it to group and continue playing, like I can in the Sonos app - am I missing something?

**Comment by ebaauw** [comment]
Not sure what you mean.  Could you post a screenshot of the scene?

Afaik, the order of characteristics in a scene is  not defined, so it might be challenging to set the coordinator and join another zone player that coordinator it in a single scene.

**Comment by mylesagray** [comment]
Sure thing - scene is here:

![Scene](https://dl.dropbox.com/s/6uz3dfv0sr9aper/IMG_2071.jpeg?dl=0)

The problem I'm having is that when I run this scene, to group all speakers - whatever is playing stops and needs manually restarted.

When I'm in the Sonos app and I group all zones the music keeps playing.

**Comment by ebaauw** [comment]
The Office Speakers are included twice?  You haven't included setting the _Power State_ of the _Kitchen Sonos_ on?

So if I understand correctly, the Kitchen Sonos was playing before you activate this scene, but stops when you activate it  The Kitchen Sonos wasn't setup as _Sonos Coordinator_.

What I think happens is that the speakers (incl. Kitchen) actually join the previous _Sonos Coordinator_ which isn't playing anything.  Or the other players don't join anything, because Kitchen is still, or has just become, a member of another group and because of that, cannot be joined.

Could you list a screenshot from the _Rooms_ view in the Sonos app from before, and from after activating this scene?  What version of homebridge-zp are you on?  Do you see any http status 500 messages in the log when activating the scene?  Can you run `homebridge -D` and list the log from when activating the scene.

I tried some tests on v1.0.7, and see that the zone player isn't leaving a group when setting _Sonos Coordinator_.  This will cause errors when subsequently trying to join other players to it.  Might actually be an issue introduced in the v1 refactor - need to check the old code.  However, when it does become the coordinator of a standalone group (because it was a member of another group), it will stop playing.

**Comment by ebaauw** [comment]
> Office Speakers are there twice because there are two Sonos zones in there

I didn't realise it was possible to have multiple zones with the same name.  This will confuse the hell out of homebridge-zp, which registers zones under the zone name.  It will take me some considerable effort to change that to registering zones under the id of the master zone player.  Even then, the Homebridge log using zone names would continue to be confusing.  For now, could you please change the name of the of the zones?

Your screenshots looks very different from the Sosos app on my devices.  Maybe because of SoundCloud?  I expected to be able to see what zone was the coordinator after the scene, instead of just "Everywhere".

> It is almost certainly a race condition that the grouping is done before the coordinator is set?

Yes.  Looking at the log, the first Office Sonos steals the role of Sonos Coordinator from the Kitchen Sonos, when the Office Speakers is turned on.
```
[7/31/2019, 12:52:26 PM] [ZP] Office Speakers: On changed from false to true
[7/31/2019, 12:52:26 PM] [ZP] Office Speakers: set On from false to true
[7/31/2019, 12:52:26 PM] [ZP] Kitchen Sonos Sonos: set Sonos Coordinator from true to false
[7/31/2019, 12:52:26 PM] [ZP] Office Sonos: set Sonos Coordinator from false to true
```
Not sure why they don't simply join the Kitchen Sonos group, maybe the Kitchen Speakers are off?  This shouldn't happen, the Speakers should be forced on when the zone player is Sonos Coordinator.

Next, the Speakers for the other players, including Kitchen are turned on, and they join the Office group:
```
[7/31/2019, 12:52:26 PM] [ZP] Office Speakers: On changed from false to true
[7/31/2019, 12:52:26 PM] [ZP] Office Speakers: set On from false to true
[7/31/2019, 12:52:26 PM] [ZP] Living Room Speakers: On changed from false to true
[7/31/2019, 12:52:26 PM] [ZP] Living Room Speakers: set On from false to true
[7/31/2019, 12:52:26 PM] [ZP] Kitchen Sonos Speakers: On changed from false to true
[7/31/2019, 12:52:26 PM] [ZP] Kitchen Sonos Speakers: set On from false to true
```

Next, the Kitchen Sonos Coordinator is switched on, and Kitchen takes over from Office:
```
[7/31/2019, 12:52:26 PM] [ZP] Kitchen Sonos Sonos: Sonos Coordinator changed from false to true
[7/31/2019, 12:52:26 PM] [ZP] Kitchen Sonos Sonos: set Sonos Coordinator from false to true
[7/31/2019, 12:52:26 PM] [ZP] Office Sonos: set Sonos Coordinator from true to false
...
[7/31/2019, 12:52:26 PM] [ZP] Office Speakers: set On from true to false
[7/31/2019, 12:52:26 PM] [ZP] Office Speakers: set On from true to false
```

I'm not sure what's happening next, I really need the `homebridge -D` output here.  I think the `GroupManagement` events are coming in, from the other zone players joining Office, and homebridge-zp copies the coordinator state.
```
[7/31/2019, 12:52:26 PM] [ZP] Living Room Sonos: set On from false to true
[7/31/2019, 12:52:26 PM] [ZP] Kitchen Sonos Sonos: set On from false to true
...
[7/31/2019, 12:52:26 PM] [ZP] Living Room Sonos: set Sonos Group from Living Room to Office
[7/31/2019, 12:52:26 PM] [ZP] Living Room Sonos: set On from true to false
[7/31/2019, 12:52:26 PM] [ZP] Living Room Sonos: set Volume from 28% to 100%
[7/31/2019, 12:52:26 PM] [ZP] Kitchen Sonos Sonos: set Sonos Group from Kitchen Sonos to Office
[7/31/2019, 12:52:26 PM] [ZP] Kitchen Sonos Sonos: set On from true to false
[7/31/2019, 12:52:26 PM] [ZP] Kitchen Sonos Sonos: set Volume from 36% to 100%
[7/31/2019, 12:52:26 PM] [ZP] Kitchen Sonos Sonos: set Track from Hybrid - Black Treacle (Summer Mixtape) to 
[7/31/2019, 12:52:26 PM] [ZP] Office Sonos: set On from false to true
[7/31/2019, 12:52:27 PM] [ZP] Office Sonos: set Volume from 100% to 31%
[7/31/2019, 12:52:27 PM] [ZP] Kitchen Sonos Sonos: set Volume from 100% to 31%
[7/31/2019, 12:52:27 PM] [ZP] Living Room Sonos: set Volume from 100% to 31%
[7/31/2019, 12:52:27 PM] [ZP] Office Sonos: set On from true to false
[7/31/2019, 12:52:27 PM] [ZP] Office Sonos: set Volume from 29% to 31%
```

However the Sonos Coordinator role is once again stolen from Kitchen.  Not sure if this is by the first or second Office Sonos.
```
[7/31/2019, 12:52:26 PM] [ZP] Kitchen Sonos Sonos: set Sonos Coordinator from true to false
[7/31/2019, 12:52:26 PM] [ZP] Office Sonos: set Sonos Coordinator from false to true
[7/31/2019, 12:52:26 PM] [ZP] Office Speakers: set On from false to true
```

**Comment by ebaauw** [comment]
I've been doing some additional testing, but it would seem that the logic around joining and leaving zone groups has become too complex over the years, even for me.   We started out with just using the `On` characteristic of the _Speaker_ service.  Later we added the `SonosCoordinator` characteristics to the _Sonos_ service.  As of v1, we added the _Input Source_ for the television accessory.

I think it's time for a redesign:
- The `On` characteristic of the _Speaker_ service should match the first input of the television accessory.  It's value is:
  - `true` when the zone is a non-coordinator member of a zone group.  In this case the input reads "`Leave `_current coordinator_"; and
  - `false` when it's a coordinator (of either a standalone group, or of a group with other members).  In this case the input reads "`Join `_target coordinator_",  unless the zone is the target coordinator, in which case the input is hidden.
- Setting the _Speaker_ service `On` matches selecting the "`Join `_target coordinator_" input: the zone joins the group of the target coordinator.  You cannot set `On` when the zone is the target coordinator.
- Clearing the _Speaker_ service `On` matches selecting the "`Leave `_current coordinator_" input: the zone becomes coordinator of a standalone group, leaving its current group.  Typically this resets the input for the new standalone group.
- Neither setting nor clearing the _Speaker_ service `On` changes the target coordinator.
- At any given time, only one zone can be the target coordinator.  This is the only zone for which the `SonosCoordinator` characteristic in the _Sonos_ service is set.
- There should always be a target coordinator, so you cannot set `Sonos Coordinator` to `false`.  You can only set `SonosCoordinator` of the new target coordinator to `true`.  The target coordinator is persisted across Homebridge restarts.
- The target coordinator should never be a non-coordinator member zone, or other zones cannot join it.  When `SonosCoordinator` is set while the zone is a member of another group, it takes over as coordinator for that group.  This will cause a brief hiccup when the group was playing, as the new coordinator starts buffering the input stream.
- To set the target coordinator from the TV accessory, select _View TV Settings_ from the _Settings_ screen.  I think this is better than using one of the unused keys in the _Remote_ widget, to prevent accidentally switching the target coordinator.

With this design, it will no longer be possible for a coordinator to abandon the group to a new coordinator by clearing `On` (because it is already false).  Instead, you first need set `SonosCoordinator` of the new coordinator, which causes `On` of the old coordinator to be set, as it becomes a member.

Normally, setting `SonosCoordinator` takes effect immediately, as the whole concept of "target coordinator" is unique to homebridge-zp.  Only when the new target coordinator was a member of a group, it takes a while to change coordinators.  In theory, I could block HomeKit during the transition (hopefully preventing it form issuing another characteristic change), but that's tricky and prone to _Unreachable_ accessories when done wrong.

Doing some testing with Eve and with Matthias' Home app, it would seem that the characteristics are applied in the order in which the were added to the scene (even thought nether app shows the order).  You might want to re-create you scene, making sure the `SonosCoordinator` is set first.

**Comment by mylesagray** [comment]
Okay I did two things and one of them seems to have fixed it - recreated the scene adding the Coordinator service first, and secondly, *not* adding the Speaker Power on service for the Sonos I wanted to be the coordinator (in this case Kitchen).

The music continued to play when executing the scene - so either it’s the order of adding the coordinator or not adding the speaker service for the target coordinator that made it work.

**Comment by ebaauw** [comment]
Cool.  I think it's the order, but as I mentioned above, there's something odd about how setting the speaker service on currently influences the target coordinator.

**Comment by ebaauw** [comment]
v1.0.8 should work according to the re-design in my post above.

**Comment by mylesagray** [comment]
Installed 1.0.8 - so now if I create a scene, regardless of order we should be good to go?

**Comment by ebaauw** [comment]
No, the order still matters, but setting the Speakers on will no longer change the sonos coordinator.
